export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const DESKTOP_ROUTE = '/desktop'
export const STATISTICS_ROUTE = '/statistics'
export const HISTORY_ROUTE = '/history'